Document: komodoedit-8.5.3-aso+dfsg
Title: Debian komodoedit-8.5.3-aso+dfsg Manual
Author: <insert document author here>
Abstract: This manual describes what komodoedit-8.5.3-aso+dfsg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/komodoedit-8.5.3-aso+dfsg/komodoedit-8.5.3-aso+dfsg.sgml.gz

Format: postscript
Files: /usr/share/doc/komodoedit-8.5.3-aso+dfsg/komodoedit-8.5.3-aso+dfsg.ps.gz

Format: text
Files: /usr/share/doc/komodoedit-8.5.3-aso+dfsg/komodoedit-8.5.3-aso+dfsg.text.gz

Format: HTML
Index: /usr/share/doc/komodoedit-8.5.3-aso+dfsg/html/index.html
Files: /usr/share/doc/komodoedit-8.5.3-aso+dfsg/html/*.html
